version: "3.4"
services:
  notaire_front:
    image: notaire_front
    container_name: notaire_front_$ENV
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: ./.env
    environment:
      ENV: $ENV
    ports:
      - $PORT:$PORT
    restart: unless-stopped